name: Build and Release Memos for FreeBSD

on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    name: Build and Release Memos
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Build Memos
        uses: vmactions/freebsd-vm@v1
        with:
          usesh: true
          release: 13.2
          prepare: |
            pkg install -y node wget curl git go121 gcc bash gawk gsed
            ln -s /usr/local/bin/go121 /usr/local/bin/go
          run: |
            export LATEST_APP=$(wget -qO- https://api.github.com/repos/usememos/memos/tags | gawk -F '["v]' '/name/{print "v"$5;exit}')
            git clone -b $LATEST_APP https://github.com/usememos/memos

      - name: Check Artifact Directory
        run: ls memos
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: memos-freebsd
          path: memos
      
      - name: Generate Release Tag
        id: tag
        run: echo "release_tag=$(wget -qO- https://api.github.com/repos/usememos/memos/tags | gawk -F '["v]' '/name/{print "v"$5;exit}')" >> $GITHUB_ENV
      
      - name: Create Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag.outputs.release_tag }}
          files: |
            memos
      
      - name: Delete Workflow Runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          retain_days: 1
          keep_minimum_runs: 8
