name: Build Memos

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Memos
    steps:
      - uses: actions/checkout@v4

      - name: Set Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Build Memos-FreeBSD
        uses: vmactions/freebsd-vm@v1
        with:
          usesh: true
          release: 13.2
          prepare: |
            pkg install -y node npm wget curl git go121 gcc bash gawk gsed
            ln -s /usr/local/bin/go121 /usr/local/bin/go
          run: |
            cd memos
            go mod tidy
            go build -o memos-freebsd ./bin/memos/main.go
            cd ..

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: Memos-FreeBSD-${{ env.LATEST_APP }}
          path: |
              memos/memos-freebsd

      - name: Generate release tag
        id: tag
        run: echo "release_tag=${LATEST_APP}" >> $GITHUB_ENV

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.release_tag }}
          files: |
            memos/memos-freebsd

      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          retain_days: 1
          keep_minimum_runs: 8
